name: Publish Dev Packages

on:
  push:
    branches:
      - develop_dep

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build:all

      - name: Publish dev packages
        run: npm run publish:dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
