name: Publish Latest Packages

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build:all

      - name: Publish latest packages
        run: npm run publish:latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
