name: Publish Prod Package

on:
  release:
    types: [released]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Configure Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Project Dependencies
        run: npm install

      - name: Execute Rollup Build Process
        run: npm run rollup

      - name: Deploy Package to NPM Registry
        run: npm dist-tag add @ynssenem/lext@$(node -p "require('./package.json').version") latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
